fix: multiple instances
hamlet-io/cloudfront-authorization-at-edge pull request #1
Opened 2021-04-20 11:53 UTC by ml019

*Description of changes:*
Place configuration within the scope of each instance rather than at the component level.

If multiple calls to the cfcognito module were made, link information for one call would override the information for the others. By moving under the instance, values will not override each other.

2021-04-20 12:01 UTC, roleyfoley commented
As discussed this might be better with just the links under the instance. This allows for people to define their own instances in their solution from a single module instance and then just modify the link configuration on the new instances

2021-04-20 12:02 UTC, roleyfoley requested changes
minor typo and comments around instances

2021-04-20 12:02 UTC, roleyfoley commented on hamlet/cfcognito/modules/cdnlambda/module.ftl
> +            "Description" : "The instance id of the CDB to create",
```suggestion
            "Description" : "The instance id of the CDN to create",
```

2021-04-20 12:14 UTC, ml019 commented
I moved all the cdn config under instance as there were multiple references to the lambda CDN links.

2021-04-21 00:52 UTC, ml019 commented
Closing. Module changed to expect all instances of the primary cdn to share the same userpool client.  As a result, there is only one set of lambda functions per usage of the module.

If a cdn requires a different userpool client, then a different cdn component must be created so that a separate set of lambda (with different injected config) can be created.

2021-04-21 00:52 UTC, closed without merging